#!/bin/bash

set -e

if [ ! -f /etc/ssh/keys/ssh_host_ed25519_key ]
then
  ssh-keygen -t ed25519 -f /etc/ssh/keys/ssh_host_ed25519_key -N ''
fi

if [ ! -f /etc/ssh/keys/ssh_host_rsa_key ]
then
  ssh-keygen -t rsa -b 4096 -f /etc/ssh/keys/ssh_host_rsa_key -N ''
fi

exec /usr/sbin/sshd -D -e
